theme: jekyll-theme-hacker

# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://striverpan.github.io
date_format: "ordinal"
title: 潘公子爱太极
subtitle: 潘公子爱太极的博客
description: 潘公子爱太极的博客之家
keywords: 潘公子,太极,tachi
favicon: /favicon.ico
timezone: Asia/Chengdu
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: StriverPan
#organization: OPPO, Inc.
#organization_url: http://www.oppo.com
github_username: striverpan
location: Chengdu, China
email: 616358337@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: striverpan/striverpan.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie


# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
